config/routes.rb
UpDown::Application.routes.draw do
  resources :users
  resource :sessions
  resources :outfits

  root 'sessions#new'

end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
	belongs_to :user
	has_attached_file :photo, :styles => { :thumb => "100x100#", :medium => "500x500>", :large => "800x800>" }
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

	def thumb_url
		photo.url(:thumb)
	end
end

app/models/user.rb
# require "bcrypt"
class User < ActiveRecord::Base
  has_many :outfits
  has_secure_password

  validates_presence_of :email, :password, :password_confirmation
  #, :phone_number, :reference_contact, :address, :city, :state, :zip
  # def password
  #     @password
  #   end

  #   def password=(new_password)
  #     @password = new_password
  #     self.password = BCrypt::Password.create(new_password)
  #   end

  #   def authenticate(test_password)
  #     if BCrypt::Password.new(self.password) == test_password
  #       self
  #     else
  #       false
  #     end
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  respond_to :json, :html
  def index
    @outfits = Outfit.all.reverse
    respond_with @outfits
  end

  def new
    @outfit = Outfit.new
  end

  def edit
    @outfit = current_user.outfits.find(params[:id])
  end

  def create
    @outfit = Outfit.new(set_params)
    @outfit.user_id = current_user.id
    if @outfit.save
      respond_to do |format|
        format.html {redirect_to @outfit }
        format.json {render json: @outfit, status: :created}
      end
    else
      respond_to do |format|
        format.html {redirect_to 'new'}
        format.json {render json: @outfit.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @outfit = current_user.outfits.find(params[:id])
    if @outfit.update_attributes(set_params)
      respond_to do |format|
        format.html {redirect_to outfits_path }
        format.json {render nothing: :true, status: :no_content}
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
        format.json {render json: @outfit.errors, status: :unprocessable_entity}
      end
    end
  end

  def show
    @outfit = current_user.outfits.find(params[:id])
    respond_with @outfit
  end

  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    respond_to do |format|
      format.html {redirect_to  :root}
      format.json {render json: {head: :ok}}
    end
  end


protected

  def set_params
    params.require(:outfit).permit(:type_of_outfit, :occasion, :brand_name, :price, :accessories, :sender_comment, :photo)
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to outfits_path
    end
  end

  def destroy
    session.delete(:remember_token)
    redirect_to outfits_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html

  # /you.json give you the current user
  # def you
  #   respond_with current_user
  # end

    # /users.json
  def index
    @users = User.all
    respond_with @users
  end

  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      respond_to do |format|
        format.html {redirect_to outfits_path}
        format.json {render nothing: true, status: :no_content}
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
        format.json {render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:remember_token] = @user.id
      @current_user = @user
      respond_to do |format|
        format.html {redirect_to outfits_path}
        format.json {render json: @user, status: :created}
      end
    else
      respond_to do |format|
        format.html {redirect_to 'new'}
        format.json {render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = user.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to :root}
      format.json {render json: {head: :ok}}
    end
  end

  protected

  def user_params
    params.require(:user).permit(:user_name, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
    if !current_user
      flash[:danger] = "You must sign in"
      redirect_to new_sessions_path
    end
  end

  def sign_out
    session.delete(:remember_token)
    @current_user = nil
  end

  def sign_in(user)
    session[:remember_token] =user.id
    @current_user = user
  end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <!-- <link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'> -->
    <link href='http://fonts.googleapis.com/css?family=Nothing+You+Could+Do|IM+Fell+English' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= javascript_include_tag "application" %>
    <div class="contain-to-grid sticky">
      <nav class="top-bar" data-topbar data-options="sticky_on: large">
        <ul class="title-area">
          <li class="name">
            <h1><a href="#">UpDown</a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="active"><a href="/outfits">Show an Outfit!</a></li>
            <li class="has-dropdown">
              <a href="#">Menu</a>
              <ul class="dropdown">
                <% if current_user %>
                <li><%link_to "My Outfits", outfits_path%></li>
                <li><a href="#">Friends</a></li>
                <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
                <% else %>
                <li><%= link_to "Sign In", new_sessions_path%></li>
                <li><%=link_to "Sign Up", new_user_path%></li>
                <%end%>
              </ul>
            </li>
          </ul>

          <!-- Left Nav Section -->
          <!-- ul class="left">
            <li><a href="#">Left Nav Button</a></li>
          </ul> -->
        </section>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/outfits/_form.html.erb
<%= form_for @outfit do |f| %>
 <%= f.text_field :type_of_outfit, placeholder: "Piece of Clothing"%>
 <%= f.text_field :occasion, placeholder: "Type of Occasion"%>
 <%= f.text_field :brand_name, placeholder: 'Brand Name'%>
 <%= f.text_field :price, placeholder: 'Price'%>
 <%= f.text_field :accessories, placeholder: 'Type of Accessories'%>
 <%= f.text_area :sender_comment, placeholder: 'Comment'%>
 <%= f.submit 'Done'%>
<%end%>

app/views/outfits/edit.html.erb
<h1>Edit Outfit</h1>
<%= render 'form'%>

app/views/outfits/index.html.erb
<!-- <h1>My Outfits</h1> -->
<!--
<%# @outfits.each do |o|%>
<strong>Type of Outfit:</strong><br>
<%#= o.type_of_outfit %><br>
<strong>Occasion:</strong><br>
<%#= o.occasion %><br>
<strong>Brand Name:</strong><br>
<%#= o.brand_name %><br>
<strong>Price:</strong><br>
<%#= o.price %><br>
<strong>Accessories:</strong><br>
<%#= o.accessories %><br>
<strong>Comments:</strong><br>
<%#= o.sender_comment %><br><br>
<%#end%>
<br>
 -->

<%= form_for(Outfit.new , html: { multipart: true }) do |f|%>
  <%= f.file_field :photo%>
  <%= f.submit%>
<%end%>

<div ng-app="outfit-app" ng-controller="OutfitCtrl" class="container" >
    <h1 class="page_titles">Outfits</h1>
    <div class="form-group">
      <input ng-model="searchOutfit" name="searchbox" type="text" class="form-control search" id="searchbar" placeholder="Search">
    </div><br>
    <div class="scroll">
      <div id="resultsfield" ng-repeat="outfit in outfits | filter:searchOutfit ">
        <div id="outfitcontainer">
          <div id="outfitimage">
                <a href='{{outfit.photo}}'><img src='{{outfit.thumb_url}}' /></a>
          </div>
          <div id="content" ng-hide="oufit.details">
            <div id="typeofclothing">
              <div class="outfitslabel">
                <p class="size"><strong>Type of Clothing</strong></p>
              </div>
              <div class="content">
                <p>{{outfit.type_of_outfit}}</p>
              </div>
            </div>
            <div id="occasion">
              <div class="outfitslabel">
                <p class="size"><strong>Occasion</strong></p>
              </div>
              <div class="content"><p>{{outfit.occasion}}</p></div>
            </div>
            <div id="brand">
              <div class="outfitslabel">
                <p class="size"><strong>Brand</strong></p>
              </div>
              <div class="content">
                <p>{{outfit.brand}}</p>
              </div>
            </div>
            <div id="price">
              <div class="outfitslabel">
                <p class="size"><strong>Price</strong></p>
              </div>
              <div class="content">
                <p>{{outfit.price}}</p>
              </div>
            </div>
            <div id="accessories">
              <div class="outfitslabel"><p class="size"><strong>Accessories</strong></p></div>
              <div class="content"><p>{{outfit.accessories}}</p></div>
            </div>
            <div id="sendercomment">
              <div class="outfitslabel"><p class="size"><strong>Comments</strong></p></div>
              <div class="content"><p>{{outfit.sender_comment}}</p></div>
            </div>
          </div>
          <br>
          <div>
            <span ng-hide="outfit.editing">
              <a ng-click="editOutfit(outfit);" class="btn btn-info"> EDIT </a>
            </span>
            <span ng-show="outfit.editing">
              <a ng-click="backOutfit(outfit);" class="btn btn-info"> BACK </a>
            </span>
            <span>
              <a ng-click="deleteOutfit(outfit);" class="btn btn-info"> DELETE </a>
            </span>
          </div>
        </div>


        <div ng-show="outfit.editing" id="edit">
          <form class="form-group" id="outfits">
            <div>
              <input ng-model="outfit.type_of_outfit" type="text" name="type_of_outfit" class="form-control" placeholder="Type of Outfit">
            </div>
            <div>
              <input ng-model="outfit.occasion" type="text" name="occasion" class="form-control" placeholder="Occasion">
            </div>
            <div>
              <input ng-model="outfit.brand_name" type="text" name="brand_name" class="form-control" placeholder="Brand Name">
            </div>
            <div>
              <input ng-model="outfit.price" type="text" name="price" class="form-control" placeholder="Price">
            </div>
            <div>

              <input ng-model="outfit.accessories" type="text" name="accessories" class="form-control" placeholder="Accessories">
            </div>
            <div>
              <input ng-model="outfit.sender_comment" type="text" name="sender_comment" class="form-control" placeholder="Comment">
            </div>

            <div>
            <button type="submit" ng-click="updateOutfit(outfit)" class="btn btn-primary large">Update</button>
          <!--   <button type="submit" ng-click="backOutfit(outfit)" class="btn btn-primary small">Back</button> -->
            </div>
          </form>
        </div>
      </div>
    </div>
</div>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>
<%= render 'form' %>

app/views/outfits/show.html.erb
<%= image_tag @outfit.photo.url(:thumb) %>

<%= render 'form' %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container" id="newuser">
  <section id="signup">
    <h1>Sign up for free account!</h1>
      <div id= "signupform">
        <%= form_for @user do |f| %>
        	<%= f.text_field :user_name, placeholder: "Username"%>
        	<%= f.text_field :name, placeholder: "Name"%>
        	<%= f.text_field :email, placeholder: "Email"%>
        	<%= f.text_field :password, placeholder: "Password"%>
        	<%= f.text_field :password_confirmation, placeholder: "Password confirmation" %>
        	<%= f.submit 'Done'%>
        <%end%>
    </div>
  </section>
</div>